[project]
name = "toysql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.10.5",
]

[dependency-groups]
dev = [
    "icecream>=2.1.4",
]
